### PR TITLE
Expose the new `junit` config option to Kitchen

### PR DESCRIPTION
**Pull request by coderanger**
The Test Kitchen side of https://github.com/chef/inspec/pull/1859.

This allows the follow in a Kitchen config to get a Jenkins-able file to ingest:

```yaml
verifier:
  name: inspec
  junit: true
```

### CODE REVIEW

**Comment by daks** [comment]
Any news about this functionality?

**Comment by giant-atomic-monster** [comment]
I could really use this when running kitchen from CI. Thanks @coderanger

**Comment by aaronlippold** [comment]
would we also not need to add a place to point to the `json` that has the config ... where do I say here is my json config file ...

**Comment by chris-rock** [comment]
Thank you @coderanger for highlighting the use case. We exposed InSpec's reporter capabilities to kitchen with #183 which allows us to use all inspec reporters via kitchen.  The use case of your PR is covered via

```
    verifier:
      reporter:
        - progress
        - junit:/tmp/%{platform}_%{suite}_inspec.xml
        - json:/tmp/%{platform}_%{suite}_inspec.json
```
Therefore I am going to close this PR.

**Pull request closed without merging**
