### PR TITLE
Pass in extra inspec attributes, support bastion from transport options

### PR DESCRIPTION
**Pull request by frezbo**

### CODE REVIEW

**Comment by jonathanmier** [comment]
Any update on this?

**Comment by tas50** [comment]
@frezbo Can you add documentation to the readme for these new options.

**Comment by tas50** [comment]
@frezbo any chance you can open a mini-PR for just the doc change. I want people to know about this. If it's buried in the codebase it's only useful to those that poke through it.

**Comment by frezbo** [comment]
@tas50 where does the doc live, I found the transport options from the chef docs probably or the the kitchen source code.

**Comment by tas50** [comment]
Just the readme here in this repo.

**Pull request merged**
